layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

# topics:
#   - name: Coordinating Search with Foundation Models and Multi-Agent Reinforcement Learning in Complex Environments
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png


publications:
  - title: Coordinating Search with Foundation Models and Multi-Agent Reinforcement Learning in Complex Environments
    authors:
      - "Christopher Allred"
      - "Jacob Haight"
      - "Chandler Justice"
      - "Isaac Peterson"
      - "Rosario Scalise"
      - "Ted Hromadka"
      - "Jason Pusey"
      - "Mario Harper"
    link: https://ieeexplore.ieee.org/document/10818085
    journal: 2024 Eighth IEEE International Conference on Robotic Computing (IRC)
    year: 2024